### ISSUE TITLE
Suggestionsi for Furniture Locksi!!

### ISSUE THREAD

**Issue by Flloppis** [gamendegamer321/Lethal-Admin#15]
Allowin'a whitelist offa peoples who can move objects inna ship!!
For trustedi friends!!

**Comment by Flloppis** [comment]
Oh!! And whitelistsi for other features like tha- Routin' restrictions, Store purchasesii, Moon landing locks!!

**Comment by gamendegamer321** [comment]
I'll look into it for the furniture as I already know I can see which player is trying to move it.
For some of the other things (like terminal commands) I can't see which player is trying to perform the action.

I'm still planning to look into the networking but I unfortunately haven't found the time for it yet.

**Comment by Flloppis** [comment]
Inna tha news update- Wha doess tha Whitelists tabs do? o,o

**Comment by gamendegamer321** [comment]
Currently the whitelist does not do anything, although you can already add people to the whitelist. I messed up a little by not putting it on a separate branch so it was easier to add my current progress to the newest update instead of removing it and releasing without the whitelist.
The plan is to have whitelisted people bypass (most of) the restrictions you can set with lethal admin (like moving furniture), but that part is not implemented yet.

**Comment by gamendegamer321** [comment]
Added in 1.8.0
