### ISSUE TITLE
[ISSUE] Button will disappear and setting tab malfunction when re-create a lobby

### ISSUE THREAD

**Issue by CoolLKKPS** [gamendegamer321/Lethal-Admin#21]
same as topic, really, i mean really simple to reproduce

**Comment by CoolLKKPS** [comment]
@gamendegamer321

**Comment by CoolLKKPS** [comment]
this glitch is already present in 2 or maybe 3 times versions

**Comment by gamendegamer321** [comment]
Oh, that's my mistake, I only generate it the first time but when leaving and rejoining/hosting all the UI needs to be created again. It should be fixed now.
As for the settings tab I don't have any problems with it, can you maybe provide more information? Or has it been fixed in the newest version (1.7.2)?

**Comment by CoolLKKPS** [comment]
those issues are fixed! thx for ur respond!
