### ISSUE TITLE
Move the button

### ISSUE THREAD

**Issue by Paradox75831004** [gamendegamer321/Lethal-Admin#28]
Two mods use the button in one place, which is why I can't copy the id when I need it. If you can somehow move the button, it would be good.
![image](https://github.com/user-attachments/assets/b0b9f736-bc58-47df-bd60-3e5ba78cb30b)
![image](https://github.com/user-attachments/assets/341f06e8-3d51-4eed-9de2-e92a6164fadc)
https://github.com/1A3Dev/LC-LobbyImprovements/issues/1

**Comment by gamendegamer321** [comment]
Because the position is also depended on your screen size, and I can't keep moving it around for every mod. There is an option in the config to change the height at which the button appears: <code>buttonHeight</code>.

If you have the UI opened, the option is also in the settings tab which allows you to preview your changes before saving them.

**Comment by Paradox75831004** [comment]
> Because the position is also depended on your screen size, and I can't keep moving it around for every mod. There is an option in the config to change the height at which the button appears: `buttonHeight`.
> 
> If you have the UI opened, the option is also in the settings tab which allows you to preview your changes before saving them.

Got it, thanks for the info!
