### ISSUE TITLE
[BUG] if the minimum number of votes required for ship depart early are not set to 1, the ship will never leave early

### ISSUE THREAD

**Issue by CoolLKKPS** [gamendegamer321/Lethal-Admin#9]
It seems that there has less feedback here, and there is a very obvious BUG:
1. if minvotes value are equal or lower than 1, should use default value
2. if set minvotes value are higher than 1, then current vote number will set to "0 - minvotes value + 1"; and if the current vote number are not equal to 1, then do nothing; else add "minvotes value -1" to the current vote number (votes are from host) and set this function false to prevent this rule repeat again, and reset this rule to true after start a new day (in orbit); also should have a checker for poor rig, if current vote number value are higher than 1, and the minvotes setting are higher than 1, then run a timer (the timer can be canceled), after timer completed, will trigger add "minvotes value -1" to the current vote number

**Comment by gamendegamer321** [comment]
Thanks for making the bug report, although I'm not sure I understand exactly what the bug is or your solution.

Am I correct to assume your bug is: even after every dead player has voted **and** the minVotes treshold has been reached, the game still doesn't trigger the early ship depart?

Your first point is already implemented. Whenever you have the value for minVotes set to 1 or lower, none of the code for the minVotes will run. This was done to ensure that, if there is a bug with the minVotes system, you can disable the entire system (and still use the early departs) by setting the value to 1.

As for your second point I'm not sure I fully understand the proposed solution. Can you maybe provide some more information on it or maybe even an example scenario?

# Example?
As I currently understand the proposed solution it works as follows (definetly correct me if I'm wrong here):
I'll assume minVotes is set to 2 in this case (as with lower values it will not run), and we are using a bigger lobbies mod with 5 players (only important for the "checker for poor rig").

> if set minvotes value are higher than 1, then current vote number will set to "0 - minvotes value + 1";

So at the start of the day we have `currentVotes = 0 - minVotes + 1 = 0 - 2 + 1 = -1`.

> and if the current vote number are not equal to 1, then do nothing; else add "minvotes value -1" to the current vote number (votes are from host) and set this function false to prevent this rule repeat again, and reset this rule to true after start a new day (in orbit); 

In this case `minVotes = 2` so we do nothing.

> also should have a checker for poor rig, if current vote number value are higher than 1, and the minvotes setting are higher than 1, then run a timer (the timer can be canceled), after timer completed, will trigger add "minvotes value -1" to the current vote number

I don't exactly get the point of this? With the `minVotes = 2` we start the day with `currentVotes = -1`. Let's say that after a while 4 players have died. Of these 4 dead players, 3 have voted, this would put our currentVotes total at `currentVotes = 2`. Because this is higher than 1 and our minVotes is higher than one, this will start a timer (which can be canceled). After the timer is finished it will add another `minVotes - 1` to the currentVotes , in this case that would put our currentVotes at `currentVotes = 3`.

Now I see it going two different ways and I'm not sure which one you mean:

## 1.
After the currentVotes has been set to 3, the game will start an early ship depart (which still takes an ingame hour) as having `currentVotes = 3` is also what you would get if all 4 spectators voted. or

## 2.
After the currentVotes has been set to 3, the timer runs *again*. After the timer is finished it will add `minVotes - 1` to the currentVotes again, which will then be set to 4. As the amount of dead players is now equal to the amount of votes (both are 4) the game will start an early ship depart (which still takes an ingame hour)

**Comment by CoolLKKPS** [comment]
@gamendegamer321 the checker only apply if skipped currentVotes = 1, should't be hard, but that's not the perfect solution
disregard early vote mod can able to decline the depart request even currentVotes are reached requestVotes, so user can always see the correct currentVotes value, and only accept the depart request if reached minVotes, i have a poor rig with FX-8300 CPU so

**Comment by CoolLKKPS** [comment]
the checker only will apply if skipped currentVotes = 1 or the checker already apply

if minVotes = 2
4 people dead but only 1 people voted: currentVotes = 0
4 people dead but 2 people voted: currentVotes = 1 (trigger currentVotes = 1, add 2-1, result is 2, set this rule and the checker to false and cancel timer)
4 people dead but 3 people voted, but trigger glitch that skipped previous rule: currentVotes = 2 (checker apply, add 2-1, result is 3, set this rule to false)
if minVotes = 1
4 people dead but only 1 people voted: currentVotes = 1 (trigger currentVotes = 1, add 1-1, result is 1, set this rule and the checker to false and cancel timer)

but that's my logical, u might can do more better so, i will continue support u

**Comment by gamendegamer321** [comment]
Thank you for adding some more clarification on your proposed solution, although I would like to know whether or not I understand the bug in the first place. So your bug is that, the game does not start an early departure when the minVotes threshold has been reached **and** all the dead players have voted?

**Comment by CoolLKKPS** [comment]
yes and for unknown reasons

**Comment by CoolLKKPS** [comment]
so if can, make the mod to check dead player count, only call the autopliot if have enough people dead and voted, so that can able to see the correct votes count

**Comment by gamendegamer321** [comment]
Sorry it took so long to respond, I've been quite busy the past few days.
I've tried reproducing the bug but I'm unable to, can you maybe provide steps on how to reproduce it?

I already tried it by doing:
*4 players in the game and a MinVotes of 2.*
First I killed player # 1.
After having made player # 1 vote, ship did not depart (expected behaviour as the MinVotes threshold has not been reached).
Then I killed both player # 2 and player # 3.
After having player # 2 also vote, the ship did not depart (expected behaviour as not all spectators have voted).
After having player # 3 also vote, the ship did depart (expected behaviour as **both** thresholds have been reached).

**Comment by CoolLKKPS** [comment]
uh idk now, so host fixes mod did also have this function, that can show correct current votes, maybe that bc not everyone voted but idk, i just listen to my teammate, they tell me everyone voted my game are glitched

**Comment by CoolLKKPS** [comment]
@gamendegamer321 i will let u know if this issue happen again, but can u make the mod display the correct vote count?

**Comment by gamendegamer321** [comment]
Yeah I've already been working on that, I only need to test if my current implementation works but it will be there in the next update.
